name: build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu:
    runs-on: ubuntu-24.04
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install WasmEdge
        run: |
          wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.0
      - name: Bazel Test
        run: |
          bazel test //... \
            --action_env=CPATH=$HOME/.wasmedge/include \
            --action_env=LIBRARY_PATH=$HOME/.wasmedge/lib \
            --action_env=LD_LIBRARY_PATH=$HOME/.wasmedge/lib \
            --linkopt=-L$HOME/.wasmedge/lib \
            --repo_env=CC=gcc \
            --@io_bazel_rules_go//go/config:pure=false

  build_macos:
    runs-on: macos-14
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install WasmEdge
        run: |
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.0
      - name: Bazel Test
        run: |
          bazel test //... \
            --action_env=CPATH=$HOME/.wasmedge/include \
            --action_env=LIBRARY_PATH=$HOME/.wasmedge/lib \
            --action_env=DYLD_LIBRARY_PATH=$HOME/.wasmedge/lib \
            --linkopt=-L$HOME/.wasmedge/lib \
            --@io_bazel_rules_go//go/config:pure=false