name: build
on:
  push:
    branches:
      - "**" # This ensures it runs on your fork's test branch
jobs:
  build_ubuntu:
    runs-on: ubuntu-24.04
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install WasmEdge
        run: |
          wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.0
          # This makes the variables persist for the BAZEL step
          echo "CPATH=$HOME/.wasmedge/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$HOME/.wasmedge/lib" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/.wasmedge/lib" >> $GITHUB_ENV
      - name: Bazel Test
        run: bazel test //... --@io_bazel_rules_go//go/config:pure=false

  build_macos:
    runs-on: macos-14
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install WasmEdge
        run: |
          # Use curl for macOS
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.0
          echo "CPATH=$HOME/.wasmedge/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$HOME/.wasmedge/lib" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$HOME/.wasmedge/lib" >> $GITHUB_ENV
      - name: Bazel Test
        run: bazel test //... --@io_bazel_rules_go//go/config:pure=false